from stratums.stratum import Stratum
from stratums.stratum_ethash import StratumEthash
from stratums.stratum_kawpow import StratumKawpow
from stratums.stratum_blake3 import StratumBlake3
from stratums.stratum_meowpow import StratumMeowpow
from stratums.stratum_smart_mining import StratumSmartMining